
name: example-cron
on:
  schedule:
    # runs tests every 5 minutes
    - cron: "*/5 * * * *"


jobs:
  nightly:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@main
           
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust based on your requirements
    
      - name: Run pytest
        run: |
          pytest --maxfail=5  # Adjust pytest command as per your needs
